[package]
name = "registry"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
redb = "2.6.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_bytes = "0.11.19"
serde_json = "1.0.145"
tempfile = "3.23.0"
thiserror = "2.0.17"
